apiVersion: v1
kind: Service
metadata:
  namespace: efk-xpack
  name: apm-server
  labels:
   app: apm-server
spec:
  selector:
    app: apm-server
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 31001
  type: NodePort
