apiVersion: v1
kind: Service
metadata:
  namespace: efk-xpack
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 32602
  selector:
    app: kibana
